language: generic 
sudo: required
dist: xenial
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
          - libcurl4-openssl-dev
          - libev-dev
          - libsqlite-dev
          - libmysqlclient-dev
          - libboost-all-dev
          - flex
          - bison
          - pkg-config
before_script:
- wget https://ftp.fau.de/apache/thrift/0.13.0/thrift-0.13.0.tar.gz
- tar -xzf thrift-0.13.0.tar.gz
- pushd thrift-0.13.0 && ./configure --prefix=/usr --with-php=no --with-erlang=no --with-go=no --with-java=no --with-python=no --with-py3=no --with-ruby=no --with-cpp=yes && make && msudo make install && popd
script:
- mkdir build
- cd build
- cmake .. && make
